#! /usr/bin/python3

#python chapter 6 pw program. Run the program with the username as first argument to copy password, ie 'gmail'

PASSWORDS = {'email': 'johncena94', 'gmail': 'gmailpass94', 'facebook': 'thezuck94'}

import sys, pyperclip
if len(sys.argv) < 2:
    print('Usage: python pw.py [account] - copies password')
    sys.exit()

account = sys.argv[1]

if account in PASSWORDS:
		pyperclip.copy(PASSWORDS[account])
		print('Pass for ' + account + ' copied')
else:
	print('No account found')
